### ISSUE TITLE
'Cannot switch to old mode now.' error

### ISSUE THREAD

**Issue by nmccready** [MikeVitik/gulp-sequence2#1]
Thanks for the plugin as it seems closest to what gulp.series and gulp.parallel provide in gulp 4. Having a little trouble though please see the below.

Stack:

```
╰─○ gulp bump-@
[14:01:16] Requiring external module coffee-script/register
[14:01:18] Using gulpfile ~/code/github/thirdparties/ui-leaflet-draw/gulpfile.coffee
[14:01:18] Starting 'bump-@'...
{ semverLevel: '', doCommit: undefined, dryRun: undefined }
[Function]
[14:01:18] Starting 'clean'...
[14:01:18] Finished 'clean' after 15 ms
[14:01:18] Starting 'build'...
[14:01:18] Finished 'build' after 307 ms
[14:01:18] { [Error: Cannot switch to old mode now.]
  name: 'Error',
  message: 'Cannot switch to old mode now.',
  stack: 'Error: Cannot switch to old mode now.\n  at emitDataEvents (/Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:770:11)\n  at DestroyableTransform.Readable.resume (/Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:755:3)\n  at fromReadable (/Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/stream-to-promise/index.js:19:29)\n  at streamToPromise (/Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/stream-to-promise/index.js:10:31)\n  at toPromise (/Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/gulp-sequence2/index.js:73:20)\n  at res (/Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/gulp-sequence2/index.js:93:28)\n  at /Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/gulp-sequence2/index.js:98:29\n  at run (/Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/core-js/modules/es6.promise.js:87:22)\n  at /Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/core-js/modules/es6.promise.js:100:28\n  at flush (/Users/nem/code/github/thirdparties/ui-leaflet-draw/node_modules/core-js/modules/_microtask.js:18:9)\n  at nextTickCallbackWith0Args (node.js:436:9)\n  at process._tickCallback (node.js:365:13)\n',
  showStack: true,
  showProperties: true,
  plugin: 'sequence2' }
[14:01:18] Bumped 'bower.json' version to: 0.0.4
[14:01:18] Bumped 'package.json' version to: 0.0.4
```

original:

```js
var bump, bumpDistCommmit, bumpThis, commit, commitFiles, git, gulp, log, series;

gulp = require('gulp');

bump = require('gulp-bump');

git = require('gulp-git');

log = require('gulp-util').log;

series = require('gulp-sequence2');

require('./dist.coffee');

bumpThis = function(semverLevel, doCommit, dryRun, files) {
  var semverType, stream;
  if (doCommit == null) {
    doCommit = true;
  }
  if (dryRun == null) {
    dryRun = false;
  }
  if (files == null) {
    files = ['bower.json', 'package.json'];
  }
  stream = gulp.src(files);
  if (semverLevel) {
    semverType = {
      type: semverLevel
    };
  }
  if (dryRun) {
    log("DryRun: semverType: " + (JSON.stringify(semverType)) + " to bump");
  } else {
    stream.pipe(bump(semverType)).pipe(gulp.dest('./'));
  }
  return stream;
};

commitFiles = ['dist/*.js', 'bower.json', 'package.json', 'package.js', 'spec/**/*', 'src/**/*'];

commit = function(semverLevel, doCommit, dryRun, files) {
  if (doCommit == null) {
    doCommit = true;
  }
  if (dryRun == null) {
    dryRun = false;
  }
  if (files == null) {
    files = commitFiles;
  }
  return function() {
    var stream;
    stream = gulp.src(files);
    if (doCommit) {
      if (dryRun) {
        log("DryRun: commit: " + (semverLevel ? semverLevel : 'patch'));
        return stream;
      }
      stream.pipe(git.commit("chore(bump): Bumped " + (semverLevel ? semverLevel : 'patch')));
    }
    return stream;
  };
};

bumpDistCommmit = function(semverLevel, doCommit, dryRun) {
  var tasks;
  tasks = [];
  if (!dryRun) {
    tasks.push('build');
  }
  tasks.push(function() {
    return bumpThis(semverLevel, doCommit, dryRun);
  });
  tasks.push(commit(semverLevel, doCommit, dryRun));
  return series.apply(null, tasks);
};

['', 'minor', 'major'].forEach(function(name) {
  var taskName;
  taskName = name ? '-' + name : '';
  gulp.task("bump-@" + taskName, bumpDistCommmit(name));
});

```

Also tried the below with the same problem.
```.js
var bump, bumpDistCommmit, bumpThis, commit, commitFiles, git, gulp, log, series;

gulp = require('gulp');

bump = require('gulp-bump');

git = require('gulp-git');

log = require('gulp-util').log;

series = require('gulp-sequence2');

require('./dist.coffee');

bumpThis = function(semverLevel, doCommit, dryRun, files) {
  var semverType, stream;
  if (doCommit == null) {
    doCommit = true;
  }
  if (dryRun == null) {
    dryRun = false;
  }
  if (files == null) {
    files = ['bower.json', 'package.json'];
  }
  stream = gulp.src(files);
  if (semverLevel) {
    semverType = {
      type: semverLevel
    };
  }
  if (dryRun) {
    log("DryRun: semverType: " + (JSON.stringify(semverType)) + " to bump");
  } else {
    stream.pipe(bump(semverType)).pipe(gulp.dest('./'));
  }
  return stream;
};

commitFiles = ['dist/*.js', 'bower.json', 'package.json', 'package.js', 'spec/**/*', 'src/**/*'];

commit = function(semverLevel, doCommit, dryRun, files) {
  if (doCommit == null) {
    doCommit = true;
  }
  if (dryRun == null) {
    dryRun = false;
  }
  if (files == null) {
    files = commitFiles;
  }
  return function() {
    var stream;
    stream = gulp.src(files);
    if (doCommit) {
      if (dryRun) {
        log("DryRun: commit: " + (semverLevel ? semverLevel : 'patch'));
        return stream;
      }
      stream.pipe(git.commit("chore(bump): Bumped " + (semverLevel ? semverLevel : 'patch')));
    }
    return stream;
  };
};

bumpDistCommmit = function(arg, cb) {
  var doCommit, dryRun, ref, semverLevel, tasks;
  ref = arg != null ? arg : {}, semverLevel = ref.semverLevel, doCommit = ref.doCommit, dryRun = ref.dryRun;
  tasks = [];
  console.log({
    semverLevel: semverLevel,
    doCommit: doCommit,
    dryRun: dryRun
  });
  console.log(cb);
  if (!dryRun) {
    tasks.push('build');
  }
  tasks.push(function() {
    return bumpThis(semverLevel, doCommit, dryRun);
  });
  tasks.push(commit(semverLevel, doCommit, dryRun));
  return series.apply(null, tasks)(cb);
};

['', 'minor', 'major'].forEach(function(name) {
  var taskName;
  taskName = name ? '-' + name : '';
  gulp.task("bump-@" + taskName, function(cb) {
    return bumpDistCommmit({
      semverLevel: name
    }, cb);
  });
});
```

**Comment by MikeVitik** [comment]
Sorry for delay. I try to reproduce your problem and propably it can be related to node version and  modules do you use. Can you provide info about it?

**Comment by MikeVitik** [comment]
I found problem in your code. Instead of
```javascript
      stream.pipe(bump(semverType)).pipe(gulp.dest('./'));
```
you should rewrite to new stream assigment:
```javascript
     stream = stream.pipe(bump(semverType)).pipe(gulp.dest('./'));
```
And in other place too
```javascript
      stream = stream.pipe(git.commit("chore(bump): Bumped " + (semverLevel ? semverLevel : 'patch')));
```
